set cursorline
" set cursorcolumn
set number
set shiftwidth=4
set tabstop=4
set expandtab " Spaces instead of tabs
set scrolloff=10 " Do not let cursor scroll below or above N number of lines when scrolling.
set wrap " wrap lines. Use nowrap to invert
set incsearch
set ignorecase " Ignore capital letters during search.
set smartcase " This will allow you to search specifically for capital letters.
set showcmd " Show partial command you type in the last line of the screen.
set showmode " Show the mode you are on the last line.
set showmatch " Show matching words during a search.
set hlsearch " Use highlighting when doing a search."
set list " Show spaces when editing documents
set listchars=tab:»·,trail:·,extends:»,precedes:«,nbsp:· "Show spaces as dots?
syntax on
hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
" hi CursorColumn cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
nnoremap <Leader>c :set cursorline!<CR>
